# Run tests and send coverage report
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Maintain compatibility with 3.7 due to compatibility with tf 1.
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade wheel setuptools pip
        python -m pip install coverage coveralls
        python -m pip install -e .[cpu]
    - name: Run tests
      run: |
        python -m unittest discover -v
    - name: Generate coverage report
      run: |
        coverage run --source=auto_trainer -m unittest discover
        coverage report
    - name: Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      run: |
        coveralls
